### ISSUE TITLE
chapter-05 without-glue error

### ISSUE THREAD

**Issue by raidan00** [mikerourke/learn-webassembly#1]
Uncaught (in promise) LinkError: WebAssembly Instantiation: Import #0 module="env" function="__memory_base" error: global import must be a number or WebAssembly.Global object

emcc --version
1.38.25

Emscripten Release Notes (https://emscripten.org/docs/introducing_emscripten/release_notes.html)
v1.38.18: 11/08/2018
 - Wasm dynamic linking: Rename `tableBase/memoryBase` to
   `__table_base/__memory_base` (#7467)

**Comment by raidan00** [comment]
./emsdk install sdk-1.38.0-64bit
./emsdk activate sdk-1.38.0-64bit

**Comment by EugeneChung** [comment]
Even I modified load-wasm.js as #7467, it still shows the LinkError.
